[package]
name = "gcp_auth"
version = "0.1.4"
authors = ["Peter Hrvola <peter.hrvola@gmail.com>"]
repository = "https://github.com/hrvolapeter/gcp_auth"
description = "Google cloud platform (GCP) authentication using default and custom service accounts"
documentation = "https://docs.rs/gcp_auth/"
keywords = ["authentication", "gcp", "google"]
categories = ["asynchronous", "authentication"]
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
base64 = "0.12"
chrono = { version = "0.4", features = ["serde"] }
hyper = "0.13.5"
hyper-tls = "0.4"
log = "0.4"
rustls = "0.17"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = { version = "0.2", features = ["fs"] }
url = "2"
bytes = "0.5"
async-trait = "0.1.31"
thiserror = "1.0"
dirs = "3.0"
futures = "0.3"
